GET http://localhost:3000/posts
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTGVvIiwiaWF0IjoxNzQxNjIwMjg5LCJleHAiOjE3NDE2MjExODl9.qpbmihb_qLmPs-Ih1xl0LY9LCqaqIVQAHaOHAfpT2cY
###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTGVvIiwiaWF0IjoxNzQxNjIwMzA2fQ.yXKprvTTKGGPyiQxa8yYI1swFmI5NrPFN_sFGe2MXGU"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Leo"
}
###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTGVvIiwiaWF0IjoxNzQxNjIwMzA2fQ.yXKprvTTKGGPyiQxa8yYI1swFmI5NrPFN_sFGe2MXGU"
}